[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kitsunari"
version = "1.5.3"
description = "Modern Terminal UI for anime streaming"
authors = [{ name="Xeon", email="XeonXE1@proton.me" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "textual>=0.45.0",
    "anipy-api",
    "levenshtein==0.26.1"
]

[project.optional-dependencies]
dev = ["pytest", "pytest-asyncio"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"kitsunari.css" = ["*.css"]

[project.scripts]
kit = "kitsunari.src.__main__:run"
